# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Fabio Campolim
import json
import sys

import pytest

from lammpskill import run as R
from lammpskill.install.base import Installation
from lammpskill.script import lj_melt, render

STUB = '''import sys, os
args = sys.argv[1:]
i = args.index("-in"); j = args.index("-log")
text = open(args[i+1]).read()
steps = [l.split()[1] for l in text.splitlines() if l.startswith("run")][0]
open(args[j+1], "w").write("LAMMPS (0 Jan 2000)\\nCreated 4000 atoms\\n   Step          Temp          E_pair\\n         0   3   -6.77\\n"
                            "       %s   1.6   -4.7\\nLoop time of 0.5 on 1 procs for %s steps with 4000 atoms\\n" % (steps, steps))
open("marker.txt", "w").write(" ".join(args))
'''


def _fake(tmp_path, mpi=False, omp=False):
    stub = tmp_path / "stub.py"
    stub.write_text(STUB, encoding="utf-8")
    return Installation(route="fake", host="windows", executable=str(stub), version="0 Jan 2000", packages=("MOLECULE",) + (("OPENMP",) if omp else ()),
                        mpi=mpi, omp=omp, library=None, python_module=False, launch=(sys.executable,), distro=None, python=None)


def test_subprocess_backend_writes_input_runs_and_parses(tmp_path):
    inst = _fake(tmp_path)
    res = R.SubprocessBackend().run(lj_melt(steps=30), str(tmp_path / "case"), inst, time_limit=60)
    assert res.ok and res.backend == "subprocess" and res.thermo.last["Step"] == 30
    assert set(res.files) >= {"in.lammps", "log.lammps", "marker.txt"}
    assert (tmp_path / "case" / "in.lammps").read_text().startswith("# generated by lammps-skill")


def test_omp_and_mpi_flags_only_when_supported(tmp_path):
    inst = _fake(tmp_path, mpi=False, omp=False)
    res = R.SubprocessBackend().run(render(lj_melt(steps=10)), str(tmp_path / "c1"), inst, omp=4)
    assert res.ok and any("OPENMP" in w for w in res.warnings) and "-sf omp" not in (tmp_path / "c1" / "marker.txt").read_text()
    inst2 = _fake(tmp_path, omp=True)
    res2 = R.SubprocessBackend().run(render(lj_melt(steps=10)), str(tmp_path / "c2"), inst2, omp=4)
    assert res2.ok and "-sf omp -pk omp 4" in (tmp_path / "c2" / "marker.txt").read_text()


def test_pinned_routes_are_refused(tmp_path):
    inst = Installation(route="docker", host="docker", executable="lmp", version="?", packages=(), mpi=False, omp=False, library=None,
                        python_module=False, launch=("docker",), distro=None, python=None, extra={"pinned": True})
    with pytest.raises(NotImplementedError, match="pinned"):
        R.SubprocessBackend().run(render(lj_melt()), str(tmp_path), inst)


def test_run_auto_picks_subprocess_then_errors_without_any(tmp_path, monkeypatch):
    inst = _fake(tmp_path)
    monkeypatch.setattr(R, "_detect", lambda: [inst])
    assert R.run(lj_melt(steps=5), str(tmp_path / "auto")).backend == "subprocess"
    monkeypatch.setattr(R, "_detect", lambda: [])
    with pytest.raises(RuntimeError, match="no LAMMPS"):
        R.run(lj_melt(steps=5), str(tmp_path / "none"))


def test_run_or_load_records_then_loads_then_skips(tmp_path):
    calls = []

    def compute():
        calls.append(1)
        return {"pe": -4.7, "steps": 30}

    rec = tmp_path / "records"
    a = R.run_or_load("lj", compute, str(rec))
    assert a["source"] == "run" and a["pe"] == -4.7 and (rec / "lj.json").exists() and calls == [1]
    b = R.run_or_load("lj", compute, str(rec))
    assert b["source"] == "record" and b["pe"] == -4.7 and calls == [1]
    stored = json.loads((rec / "lj.json").read_text(encoding="utf-8"))
    assert "date" in stored and "lammps_skill" in stored

    def no_lammps():
        raise RuntimeError("no LAMMPS installation")
    c = R.run_or_load("missing", no_lammps, str(rec))
    assert c["source"] == "skip"


def test_real_run_through_subprocess(lammps_exe, tmp_path):
    res = R.run(lj_melt(steps=50), str(tmp_path / "real"), installation=lammps_exe, time_limit=300)
    assert res.ok, res.stderr + "\n".join(res.errors)
    assert res.thermo.last["Step"] == 50 and res.log.natoms == 4000


def test_real_mpi_run_if_the_build_has_it(lammps_exe, tmp_path):
    if not lammps_exe.mpi:
        pytest.skip("no MPI in this build")
    res = R.run(lj_melt(steps=50), str(tmp_path / "mpi"), installation=lammps_exe, mpi=2, time_limit=300)
    assert res.ok, res.stderr + "\n".join(res.errors)
    assert res.thermo.nprocs == 2 and res.thermo.last["Step"] == 50


def test_real_run_through_library_if_module(lammps_installations, tmp_path):
    inst = next((i for i in lammps_installations if i.python_module and i.python == sys.executable), None)
    if inst is None:
        pytest.skip("no in-process lammps module in this python")
    res = R.LibraryBackend().run(lj_melt(steps=20), str(tmp_path / "lib"), inst)
    assert res.ok and res.backend == "library" and res.thermo.last["Step"] == 20
