# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Fabio Campolim
import os

import numpy as np
import pytest

from conftest import FIXTURES
from lammpskill.io.box import Box
from lammpskill.io.data import ATOM_STYLE_COLUMNS, DataFile, read_data, write_data

FULL = """water box (generated by test)

3 atoms
2 atom types
2 bonds
1 bond types
1 angles
1 angle types

0.0 10.0 xlo xhi
0.0 10.0 ylo yhi
0.0 10.0 zlo zhi

Masses

1 15.9994
2 1.008

Pair Coeffs # lj/cut/coul/long

1 0.1553 3.166
2 0.0 0.0

Atoms # full

1 1 1 -0.8476 5.0 5.0 5.0 0 0 0
2 1 2 0.4238 5.8 5.6 5.0 0 0 0
3 1 2 0.4238 4.2 5.6 5.0 0 0 0

Velocities

1 0.1 0.0 0.0
2 0.0 0.2 0.0
3 0.0 0.0 0.3

Bonds

1 1 1 2
2 1 1 3

Angles

1 1 2 1 3
"""


def test_box_lengths_volume_wrap_minimum_image():
    b = Box(0, 10, 0, 10, 0, 10)
    assert b.volume == 1000 and not b.is_triclinic
    np.testing.assert_allclose(b.wrap(np.array([[11.0, -1.0, 5.0]])), [[1.0, 9.0, 5.0]])
    np.testing.assert_allclose(b.minimum_image(np.array([[9.0, -9.0, 4.0]])), [[-1.0, 1.0, 4.0]])
    t = Box(0, 10, 0, 10, 0, 10, xy=2.0)
    assert t.is_triclinic and t.matrix[1, 0] == 2.0
    assert Box.from_data_lines(t.as_data_lines()).xy == 2.0


def test_fixture_data_file_from_lammps_write_data():
    df = read_data(os.path.join(FIXTURES, "data_lj_melt.data"))
    assert df.atom_style == "atomic" and df.natoms == 4000 and df.ntypes == 1
    assert df.masses == {1: 1.0}
    assert df.positions.shape == (4000, 3) and df.velocities is not None and df.velocities.shape == (4000, 3)
    assert df.ids.min() == 1 and df.ids.max() == 4000
    assert abs(df.box.volume - 4000 / 0.8442) < 1e-3


def test_full_style_topology_and_round_trip(tmp_path):
    p = tmp_path / "w.data"
    p.write_text(FULL, encoding="utf-8")
    df = read_data(str(p))
    assert df.atom_style == "full" and df.natoms == 3 and df.counts["nbonds"] == 2 and df.counts["nangles"] == 1
    np.testing.assert_allclose(df.atoms["q"], [-0.8476, 0.4238, 0.4238])
    assert df.bonds.shape == (2, 4) and df.angles.shape == (1, 5) and df.atoms["ix"].tolist() == [0, 0, 0]
    assert df.coeffs["Pair Coeffs"][0].split()[:3] == ["1", "0.1553", "3.166"]
    out = tmp_path / "w2.data"
    write_data(df, str(out))
    df2 = read_data(str(out))
    for k in df.atoms:
        np.testing.assert_allclose(df2.atoms[k], df.atoms[k])
    np.testing.assert_allclose(df2.velocities, df.velocities)
    assert df2.bonds.tolist() == df.bonds.tolist() and df2.angles.tolist() == df.angles.tolist()
    assert df2.coeffs == df.coeffs and df2.masses == df.masses
    assert read_data(str(out)).box.volume == 1000.0


def test_unknown_style_without_comment_is_an_error(tmp_path):
    txt = FULL.replace("Atoms # full", "Atoms")
    p = tmp_path / "x.data"
    p.write_text(txt, encoding="utf-8")
    with pytest.raises(ValueError, match="atom_style"):
        read_data(str(p))
    assert read_data(str(p), atom_style="full").natoms == 3


def test_every_documented_style_has_id_and_type_and_xyz():
    for style, cols in ATOM_STYLE_COLUMNS.items():
        assert cols[0] == "id" and "type" in cols and cols[-3:] == ("x", "y", "z"), style


def test_build_and_write_from_arrays(tmp_path):
    df = DataFile.from_arrays(box=Box(0, 5, 0, 5, 0, 5), types=np.array([1, 1, 2]),
                              positions=np.array([[0, 0, 0], [1, 1, 1], [2, 2, 2]], float), masses={1: 1.0, 2: 2.0},
                              atom_style="atomic", comment="three atoms")
    out = tmp_path / "a.data"
    write_data(df, str(out))
    text = out.read_text(encoding="utf-8")
    assert text.startswith("three atoms") and "3 atoms" in text and "2 atom types" in text and "Atoms # atomic" in text


def test_round_trip_through_lammps_itself(lammps_exe, tmp_path):
    """Write a data file with our writer, let LAMMPS read it and write it back, compare (skipped without LAMMPS)."""
    from lammpskill.install.base import run_command
    df = DataFile.from_arrays(box=Box(0, 6, 0, 6, 0, 6), types=np.array([1, 1]),
                              positions=np.array([[1, 1, 1], [3, 3, 3]], float), masses={1: 1.0}, atom_style="atomic")
    write_data(df, str(tmp_path / "in.data"))
    (tmp_path / "in.rt").write_text(
        "units lj\natom_style atomic\nread_data in.data\npair_style lj/cut 2.5\npair_coeff * * 1 1\nrun 0\nwrite_data out.data\n", encoding="utf-8")
    p = run_command(lammps_exe, ["-in", "in.rt", "-log", "log.rt", "-screen", "none"], cwd=str(tmp_path), timeout=120)
    assert p.returncode == 0, p.stderr + (tmp_path / "log.rt").read_text(errors="replace")
    back = read_data(str(tmp_path / "out.data"))
    np.testing.assert_allclose(back.positions[np.argsort(back.ids)], df.positions, atol=1e-12)
