# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Fabio Campolim
import pytest

from lammpskill.script import Spec, Stage, check, eam_fcc, lj_melt, render, spce_water


def test_lj_melt_renders_in_manual_order_and_has_no_absolute_path():
    text = render(lj_melt())
    lines = [ln.split()[0] for ln in text.splitlines() if ln.strip() and not ln.startswith("#")]
    order = ["units", "atom_style", "lattice", "region", "create_box", "create_atoms", "mass", "pair_style", "pair_coeff",
             "neighbor", "neigh_modify", "velocity", "fix", "thermo", "thermo_style", "run"]
    idx = [lines.index(k) for k in order]
    assert idx == sorted(idx)
    assert "generated by lammps-skill" in text and ":\\" not in text and "/mnt/" not in text


def test_spec_round_trip_of_every_field():
    s = Spec(units="metal", atom_style="full", read_data="w.data", pair_style="lj/cut/coul/long 10.0", pair_coeffs=["* * 0 0", "1 1 0.1553 3.166"],
             bond_style="harmonic", bond_coeffs=["1 1000 1.0"], angle_style="harmonic", angle_coeffs=["1 100 109.47"], kspace_style="pppm 1e-4",
             special_bonds="lj/coul 0 0 0.5", timestep=0.001, fixes=["1 all shake 1e-4 20 0 b 1 a 1", "2 all nvt temp 300 300 0.1"],
             computes=["msd all msd"], dumps=["d all custom 100 w.dump id type x y z"], thermo=50, stages=[Stage("minimize", "1e-6 1e-8 100 1000"), Stage("run", "500")],
             write_data="final.data", groups=["ox type 1"], velocity=["all create 300 12345"], pre=["# pre"], post=["# post"])
    t = render(s)
    for frag in ("units metal", "read_data w.data", "kspace_style pppm 1e-4", "special_bonds lj/coul 0 0 0.5", "timestep 0.001",
                 "fix 1 all shake", "compute msd all msd", "dump d all custom", "minimize 1e-6 1e-8 100 1000", "run 500",
                 "write_data final.data", "group ox type 1", "# pre", "# post"):
        assert frag in t, frag
    assert t.index("group ox") < t.index("velocity") < t.index("fix 1")
    assert t.index("minimize") < t.index("run 500") < t.index("write_data")


def test_checker_finds_the_documented_mistakes():
    bad = """units real
atom_style full
read_data w.data
pair_style lj/cut/coul/long 10.0
pair_coeff * * 0.1 3.0
fix 1 all nvt temp 300 300 100
fix 1 all nve
timestep 5.0
thermo 1000
run 500
"""
    f = check(bad)
    codes = {x.code for x in f}
    assert {"C02", "C04", "C07", "C09"} <= codes          # coul/long without kspace, timestep too large for real, duplicate fix id, thermo > run
    assert all(x.manual for x in f) and all(x.line for x in f if x.code in ("C02", "C07"))
    assert [x for x in f if x.code == "C07"][0].level == "error"


def test_checker_orders_and_missing_pieces():
    bad = "units lj\natom_style atomic\nlattice fcc 0.8\nregion b block 0 5 0 5 0 5\ncreate_box 1 b\ncreate_atoms 1 box\npair_coeff * * 1 1\npair_style lj/cut 2.5\nvelocity all create 1.0 1\nrun 10\n"
    codes = {x.code: x for x in check(bad)}
    assert "C06" in codes and codes["C06"].level == "error"     # pair_coeff before pair_style
    assert "C11" in codes and codes["C11"].level == "error"     # velocity create before mass
    assert "C13" in codes and codes["C13"].level == "info"      # nothing written at the end


def test_checker_is_quiet_on_the_presets(tmp_path):
    assert [x for x in check(render(lj_melt())) if x.level == "error"] == []
    spec, df = spce_water(n_side=2, workdir=str(tmp_path))
    assert (tmp_path / "water.data").exists() and df.natoms == 3 * 8 and df.bonds.shape[0] == 16 and df.angles.shape[0] == 8
    assert [x for x in check(render(spec), workdir=str(tmp_path)) if x.level == "error"] == []


def test_checker_flags_missing_data_file(tmp_path):
    codes = {x.code for x in check("units real\natom_style full\nread_data nope.data\npair_style lj/cut 5\npair_coeff * * 1 1\nrun 0\n", workdir=str(tmp_path))}
    assert "C14" in codes


def test_eam_preset_uses_funcfl_or_setfl_by_extension():
    funcfl = render(eam_fcc(potential="Cu_u3.eam"))
    assert "pair_style eam\n" in funcfl and "pair_coeff 1 1 Cu_u3.eam" in funcfl
    assert "eam/alloy" in render(eam_fcc(potential="Cu_mishin1.eam.alloy"))
    assert "minimize" in render(eam_fcc()) and "lattice fcc 3.615" in render(eam_fcc())


def test_presets_run_in_lammps(lammps_exe, tmp_path):
    from lammpskill.install.base import run_command
    from lammpskill.io.log import read_log
    spec, _ = spce_water(n_side=2, steps=20, workdir=str(tmp_path))
    if not {"KSPACE", "MOLECULE", "RIGID"} <= set(lammps_exe.packages):
        pytest.skip("KSPACE/MOLECULE/RIGID not in this build")
    (tmp_path / "in.w").write_text(render(spec), encoding="utf-8")
    p = run_command(lammps_exe, ["-in", "in.w", "-log", "log.w", "-screen", "none"], cwd=str(tmp_path), timeout=300)
    assert p.returncode == 0, p.stderr + (tmp_path / "log.w").read_text(errors="replace")[-1500:]
    lf = read_log(str(tmp_path / "log.w"))
    assert lf.errors == [] and lf.thermo.last["Step"] == 20
