# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Fabio Campolim
"""Extract every figure of the executed chapter notebooks into course/deck/figs/.

Rule 22 of the publishing playbook: every figure shown in the course is generated by a notebook
cell. This script is the only way figures enter the deck -- it pulls the PNG (static plot) and
GIF (animation, ``display(Image(filename=...))`` of a file ``lammpskill.viz.animate_gif`` wrote)
outputs of the product's chapter notebooks (``chapters/LAMMPS_NN_*.ipynb``, in the order
``build/assemble.py`` defines, after ``build/execute.py``) and writes ``provenance.json`` next to
them, mapping each file to its chapter, cell index, figure number (within that chapter -- chapters
are self-contained, unlike a continuously-numbered book) and full caption.

Figure names are ``ch<NN>-f<ordinal>.png`` or ``.gif`` (chapter key from the notebook filename,
ordinal within that chapter, extension from whichever MIME type the cell actually output), because
lammps-skill's chapter headings are not numbered sections.

Usage (from lammps-skill/):
    python course/tools/extract_figures.py            # write figures + provenance
    python course/tools/extract_figures.py --check    # exit 1 when figures are stale
    python course/tools/extract_figures.py --notebook chapters/LAMMPS_06_Structure_And_Analysis.ipynb
"""

import argparse
import base64
import hashlib
import html
import json
import os
import re
import sys

__version__ = "0.1.17"

HERE = os.path.dirname(os.path.abspath(__file__))
SKILL = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, os.path.join(SKILL, "build"))
from assemble import CHAPTERS  # noqa: E402

_CHAPTER_KEY = re.compile(r"^LAMMPS_(\d\d)_")

# every chapter notebook, in chapter order -- scanned to find which ones actually have a figure
# (00, 02, 05, 07, 08, 09, 10 have none today; a chapter with none simply contributes no records)
NOTEBOOKS = [os.path.join(SKILL, "chapters", "LAMMPS_%s_%s.ipynb" % (k, CHAPTERS[k]["slug"]))
             for k in sorted(CHAPTERS)]
FIGDIR = os.path.join(SKILL, "course", "deck", "figs")


def _html_caption(out):
    """'Figure N. text' from a display(HTML(...)) caption output, else None."""
    data = out.get("data", {})
    if "text/html" not in data:
        return None
    text = "".join(data["text/html"])
    m = re.search(r"<b>\s*Figure\s+(\d+)\.\s*</b>(.*?)</div>", text, re.S)
    if not m:
        return None
    body = re.sub(r"<[^>]+>", "", m.group(2))
    return int(m.group(1)), html.unescape(re.sub(r"\s+", " ", body)).strip()


def catalogue(notebook_paths):
    """Yield one record per PNG or GIF output of the given notebooks (a path or a list of paths,
    read in order): chapter, ordinal, cell, caption, bytes."""
    if isinstance(notebook_paths, str):
        notebook_paths = [notebook_paths]
    for path in notebook_paths:
        yield from _catalogue_one(path)


def _catalogue_one(notebook_path):
    chapter = os.path.basename(notebook_path)
    m = _CHAPTER_KEY.match(chapter)
    key = m.group(1) if m else "00"
    with open(notebook_path, encoding="utf-8") as f:
        nb = json.load(f)
    heading, ordinal = "", 0
    for idx, cell in enumerate(nb["cells"]):
        src = "".join(cell.get("source", []))
        if cell["cell_type"] == "markdown":
            for line in src.splitlines():
                if line.strip().startswith("## "):
                    heading = line.strip()[3:].strip()
            continue
        records = []
        for out in cell.get("outputs", []):
            data = out.get("data", {})
            img_key = "image/png" if "image/png" in data else "image/gif" if "image/gif" in data else None
            if img_key is not None:
                ext = "png" if img_key == "image/png" else "gif"
                png = base64.b64decode("".join(data[img_key]))
                ordinal += 1
                records.append({
                    "file": "ch%s-f%d.%s" % (key, ordinal, ext),
                    "chapter": chapter,
                    "section": 0,
                    "heading": heading,
                    "cell": idx,
                    "figure": None,
                    "caption": "",
                    "sha256": hashlib.sha256(png).hexdigest(),
                    "bytes": len(png),
                    "png": png,
                })
                continue
            cap = _html_caption(out)
            if cap:
                for r in records:
                    if r["figure"] is None:
                        r["figure"], r["caption"] = cap
                        break
        yield from records


def write(records, figdir, notebook_paths, quiet=False):
    if isinstance(notebook_paths, str):
        notebook_paths = [notebook_paths]
    os.makedirs(figdir, exist_ok=True)
    prov = {"notebooks": [os.path.basename(p) for p in notebook_paths], "figures": {}}
    for r in records:
        with open(os.path.join(figdir, r["file"]), "wb") as f:
            f.write(r["png"])
        prov["figures"][r["file"]] = {k: r[k] for k in
                                      ("chapter", "section", "heading", "cell", "figure", "caption",
                                       "sha256", "bytes")}
        if not quiet:
            print("  %s  cell %3d  %7d B  %s" % (r["file"], r["cell"], r["bytes"], r["chapter"]))
    with open(os.path.join(figdir, "provenance.json"), "w", encoding="utf-8", newline="\n") as f:
        json.dump(prov, f, indent=1, ensure_ascii=False)
        f.write("\n")
    return prov


def check(records, figdir):
    """Return a list of problems: missing, stale or orphaned figures."""
    problems = []
    prov_path = os.path.join(figdir, "provenance.json")
    if not os.path.exists(prov_path):
        return ["provenance.json missing -- run extract_figures.py"]
    with open(prov_path, encoding="utf-8") as f:
        prov = json.load(f)["figures"]
    seen = set()
    for r in records:
        seen.add(r["file"])
        path = os.path.join(figdir, r["file"])
        if not os.path.exists(path):
            problems.append("missing %s (cell %s)" % (r["file"], r["cell"]))
            continue
        with open(path, "rb") as f:
            on_disk = hashlib.sha256(f.read()).hexdigest()
        if on_disk != r["sha256"]:
            problems.append("stale %s: notebook output changed (cell %s)" % (r["file"], r["cell"]))
        if prov.get(r["file"], {}).get("sha256") != r["sha256"]:
            problems.append("provenance out of date for %s" % r["file"])
    for name in sorted(prov):
        if name not in seen:
            problems.append("orphan %s: no longer produced by the notebooks" % name)
    return problems


def build_parser():
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--notebook", nargs="+", default=NOTEBOOKS, metavar="IPYNB",
                   help="executed notebook(s) to read, in order (default: every chapter)")
    p.add_argument("--outdir", default=FIGDIR, help="figure directory (course/deck/figs)")
    p.add_argument("--check", action="store_true",
                   help="do not write; exit 1 if figures or provenance are stale")
    p.add_argument("-q", "--quiet", action="store_true")
    p.add_argument("--version", action="version", version="%%(prog)s %s" % __version__)
    return p


def main(argv=None):
    a = build_parser().parse_args(argv)
    records = list(catalogue(a.notebook))
    if not records:
        print("no PNG/GIF outputs found -- execute the notebooks first (build/execute.py)",
              file=sys.stderr)
        return 1
    if a.check:
        problems = check(records, a.outdir)
        for pr in problems:
            print(pr, file=sys.stderr)
        if not a.quiet:
            print("%d figures checked, %d problem(s)" % (len(records), len(problems)))
        return 1 if problems else 0
    prov = write(records, a.outdir, a.notebook, quiet=a.quiet)
    if not a.quiet:
        print("ok: %d figures -> %s" % (len(prov["figures"]), os.path.relpath(a.outdir, SKILL)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
