# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Fabio Campolim
"""Input scripts from a Python spec (rendered in the order the manual's "Commands_structure" page prescribes:
initialization, system definition, settings, run), presets for the chapter systems, and a checker for the mistakes
the manual warns about (each finding names its manual page). No script here is copied from LAMMPS."""

from __future__ import annotations

import os
import re
from dataclasses import dataclass, field

import numpy as np

from . import __version__
from .io.box import Box
from .io.data import DataFile


@dataclass
class Stage:
    kind: str
    args: str


@dataclass
class Spec:
    units: str = "lj"
    dimension: int = 3
    atom_style: str = "atomic"
    boundary: str = "p p p"
    lattice: str | None = None
    region: str | None = None
    create_box: int | None = None
    create_atoms: str | None = None
    read_data: str | None = None
    masses: dict = field(default_factory=dict)
    pair_style: str | None = None
    pair_coeffs: list = field(default_factory=list)
    bond_style: str | None = None
    bond_coeffs: list = field(default_factory=list)
    angle_style: str | None = None
    angle_coeffs: list = field(default_factory=list)
    dihedral_style: str | None = None
    dihedral_coeffs: list = field(default_factory=list)
    kspace_style: str | None = None
    special_bonds: str | None = None
    neighbor: str | None = None
    neigh_modify: str | None = None
    timestep: float | None = None
    groups: list = field(default_factory=list)
    velocity: list = field(default_factory=list)
    computes: list = field(default_factory=list)
    fixes: list = field(default_factory=list)
    dumps: list = field(default_factory=list)
    thermo: int = 100
    thermo_style: str = "custom step temp pe ke etotal press"
    thermo_modify: str | None = None
    stages: list = field(default_factory=lambda: [Stage("run", "100")])
    pre: list = field(default_factory=list)
    post: list = field(default_factory=list)
    write_data: str | None = None
    comment: str = ""


def render(spec: Spec) -> str:
    L = ["# generated by lammps-skill %s%s" % (__version__, (" — " + spec.comment) if spec.comment else ""), ""]
    L += spec.pre
    L += ["# --- initialization", "units %s" % spec.units, "dimension %d" % spec.dimension, "boundary %s" % spec.boundary,
          "atom_style %s" % spec.atom_style]
    L += ["", "# --- system definition"]
    if spec.lattice:
        L.append("lattice %s" % spec.lattice)
    if spec.region:
        L.append("region %s" % spec.region)
    if spec.create_box is not None:
        L.append("create_box %d %s" % (spec.create_box, (spec.region or "box").split()[0]))
    if spec.create_atoms:
        L.append("create_atoms %s" % spec.create_atoms)
    if spec.read_data:
        L.append("read_data %s" % spec.read_data)
    for t, m in sorted(spec.masses.items()):
        L.append("mass %d %.10g" % (t, m))
    L += ["", "# --- settings"]
    if spec.pair_style:
        L.append("pair_style %s" % spec.pair_style)
    L += ["pair_coeff %s" % c for c in spec.pair_coeffs]
    for name, style, coeffs in (("bond", spec.bond_style, spec.bond_coeffs), ("angle", spec.angle_style, spec.angle_coeffs),
                                ("dihedral", spec.dihedral_style, spec.dihedral_coeffs)):
        if style:
            L.append("%s_style %s" % (name, style))
            L += ["%s_coeff %s" % (name, c) for c in coeffs]
    if spec.kspace_style:
        L.append("kspace_style %s" % spec.kspace_style)
    if spec.special_bonds:
        L.append("special_bonds %s" % spec.special_bonds)
    if spec.neighbor:
        L.append("neighbor %s" % spec.neighbor)
    if spec.neigh_modify:
        L.append("neigh_modify %s" % spec.neigh_modify)
    if spec.timestep is not None:
        L.append("timestep %.10g" % spec.timestep)
    L += ["group %s" % g for g in spec.groups]
    L += ["velocity %s" % v for v in spec.velocity]
    L += ["compute %s" % c for c in spec.computes]
    L += ["fix %s" % f for f in spec.fixes]
    L += ["dump %s" % d for d in spec.dumps]
    L += ["thermo %d" % spec.thermo, "thermo_style %s" % spec.thermo_style]
    if spec.thermo_modify:
        L.append("thermo_modify %s" % spec.thermo_modify)
    L += ["", "# --- run"]
    for st in spec.stages:
        L.append("%s %s" % (st.kind, st.args))
    if spec.write_data:
        L.append("write_data %s" % spec.write_data)
    L += spec.post
    return "\n".join(L) + "\n"


# ---------------- presets (parameters cited in references/benchmarks.md; nothing copied) ----------------

def lj_melt(n=10, rho=0.8442, T=3.0, steps=250, rc=2.5, seed=87287) -> Spec:
    return Spec(units="lj", atom_style="atomic", lattice="fcc %.6g" % rho, region="box block 0 %d 0 %d 0 %d" % (n, n, n),
                create_box=1, create_atoms="1 box", masses={1: 1.0}, pair_style="lj/cut %.6g" % rc, pair_coeffs=["1 1 1.0 1.0 %.6g" % rc],
                neighbor="0.3 bin", neigh_modify="every 20 delay 0 check no", velocity=["all create %.6g %d loop geom" % (T, seed)],
                fixes=["1 all nve"], thermo=50, thermo_style="custom step temp epair emol etotal press",
                stages=[Stage("run", str(steps))], comment="Lennard-Jones melt, reduced units")


def eam_fcc(element="Cu", a=3.615, n=4, potential="Cu_u3.eam", T=None, steps=0, minimize=True, mass=63.546) -> Spec:
    setfl = potential.endswith(".eam.alloy") or potential.endswith(".eam.fs")
    stages = []
    if minimize:
        stages.append(Stage("minimize", "1.0e-10 1.0e-10 1000 10000"))
    if steps:
        stages.append(Stage("run", str(steps)))
    if not stages:
        stages.append(Stage("run", "0"))
    fixes = ["1 all box/relax iso 0.0 vmax 0.001"] if minimize else []
    vel = ["all create %.6g 4928459 loop geom" % T] if T else []
    if T:
        fixes.append("2 all nvt temp %.6g %.6g 0.1" % (T, T))
    return Spec(units="metal", atom_style="atomic", lattice="fcc %.6g" % a, region="box block 0 %d 0 %d 0 %d" % (n, n, n), create_box=1,
                create_atoms="1 box", masses={1: mass}, pair_style="eam/alloy" if setfl else "eam",
                pair_coeffs=["* * %s %s" % (potential, element) if setfl else "1 1 %s" % potential],
                neighbor="2.0 bin", neigh_modify="delay 10 check yes", timestep=0.001, velocity=vel, fixes=fixes,
                thermo=10, thermo_style="custom step temp pe press vol lx", stages=stages, comment="EAM fcc %s" % element)


def _water_geometry():
    """SPC/E: O-H 1.0 A, H-O-H 109.47 deg (Berendsen, Grigera & Straatsma 1987)."""
    theta = np.deg2rad(109.47)
    h1 = np.array([np.sin(theta / 2), np.cos(theta / 2), 0.0])
    h2 = np.array([-np.sin(theta / 2), np.cos(theta / 2), 0.0])
    return np.zeros(3), h1, h2


def spce_water(n_side=4, spacing=3.1, T=300.0, steps=1000, workdir=None, seed=12345):
    """Rigid SPC/E water on a cubic lattice (density ~ 1 g/cm3 at spacing 3.1 A), fix shake, PPPM. Returns (Spec, DataFile)."""
    o, h1, h2 = _water_geometry()
    nmol = n_side ** 3
    box = Box(0, n_side * spacing, 0, n_side * spacing, 0, n_side * spacing)
    pos, types, q, mol, bonds, angles = [], [], [], [], [], []
    rng = np.random.default_rng(seed)
    aid = 0
    for i in range(n_side):
        for j in range(n_side):
            for k in range(n_side):
                c = (np.array([i, j, k]) + 0.5) * spacing
                u = rng.normal(size=4)
                u /= np.linalg.norm(u)
                a_, b_, c_, d_ = u
                R = np.array([[a_ * a_ + b_ * b_ - c_ * c_ - d_ * d_, 2 * (b_ * c_ - a_ * d_), 2 * (b_ * d_ + a_ * c_)],
                              [2 * (b_ * c_ + a_ * d_), a_ * a_ - b_ * b_ + c_ * c_ - d_ * d_, 2 * (c_ * d_ - a_ * b_)],
                              [2 * (b_ * d_ - a_ * c_), 2 * (c_ * d_ + a_ * b_), a_ * a_ - b_ * b_ - c_ * c_ + d_ * d_]])
                m = len(mol) // 3 + 1
                for p, t, qq in ((o, 1, -0.8476), (h1, 2, 0.4238), (h2, 2, 0.4238)):
                    pos.append(c + R @ p)
                    types.append(t)
                    q.append(qq)
                    mol.append(m)
                oid = aid + 1
                bonds += [[len(bonds) + 1, 1, oid, oid + 1], [len(bonds) + 2, 1, oid, oid + 2]]
                angles.append([len(angles) + 1, 1, oid + 1, oid, oid + 2])
                aid += 3
    df = DataFile.from_arrays(box=box, types=np.array(types), positions=np.array(pos), masses={1: 15.9994, 2: 1.008},
                              atom_style="full", comment="SPC/E water, %d molecules, generated by lammps-skill" % nmol,
                              charges=np.array(q), mol=np.array(mol))
    df.bonds, df.angles = np.array(bonds, int), np.array(angles, int)
    df.counts.update({"nbonds": len(bonds), "nbondtypes": 1, "nangles": len(angles), "nangletypes": 1})
    if workdir:
        from .io.data import write_data
        os.makedirs(workdir, exist_ok=True)
        write_data(df, os.path.join(workdir, "water.data"))
    spec = Spec(units="real", atom_style="full", read_data="water.data", pair_style="lj/cut/coul/long 10.0",
                pair_coeffs=["* * 0.0 0.0", "1 1 0.1553 3.166"], bond_style="harmonic", bond_coeffs=["1 1000.0 1.0"],
                angle_style="harmonic", angle_coeffs=["1 100.0 109.47"], kspace_style="pppm 1.0e-4",
                special_bonds="lj/coul 0.0 0.0 0.5", neighbor="2.0 bin", neigh_modify="every 1 delay 0 check yes", timestep=1.0,
                velocity=["all create %.6g %d loop geom" % (T, seed)],
                fixes=["shk all shake 1.0e-4 20 0 b 1 a 1", "nvt all nvt temp %.6g %.6g 100.0" % (T, T)],
                thermo=10, thermo_style="custom step temp pe ke etotal press", stages=[Stage("run", str(steps))],
                comment="SPC/E water, %d molecules" % nmol)
    return spec, df


# ---------------- checker ----------------

@dataclass
class Finding:
    level: str
    code: str
    message: str
    line: int | None
    manual: str


CHECKS = [
    ("C01", "warning", "units", "no `units` command: the default is `lj`; say so explicitly"),
    ("C02", "error", "kspace_style", "a `*/coul/long` (or `*/long`) pair style needs a `kspace_style`"),
    ("C03", "error", "kspace_style", "`kspace_style` without a long-range pair style"),
    ("C04", "warning", "timestep", "timestep larger than the usual limit for these units (lj 0.01, real 2.0, metal 0.005)"),
    ("C05", "error", "run", "`run` or `minimize` before any `pair_style`"),
    ("C06", "error", "pair_coeff", "`pair_coeff` before `pair_style`"),
    ("C07", "error", "fix", "fix ID used twice without `unfix`"),
    ("C08", "warning", "atom_style", "bonded atom_style (bond/angle/molecular/full) without `read_data`, `read_restart` or `molecule`"),
    ("C09", "warning", "thermo", "`thermo N` larger than the following `run M`: no thermo output at all"),
    ("C10", "warning", "dump", "dump interval larger than the total run: the dump stays empty"),
    ("C11", "error", "velocity", "`velocity ... create` before every mass is set (LAMMPS: 'All masses are not set')"),
    ("C12", "info", "timestep", "no `timestep`: the default for these units applies (lj 0.005, real 1.0, metal 0.001)"),
    ("C13", "info", "write_data", "nothing written at the end (`write_data`, `write_restart` or a dump)"),
    ("C14", "error", "read_data", "`read_data` file not found in the working directory"),
]
_MAX_DT = {"lj": 0.01, "real": 2.0, "metal": 0.005}
_LONG_PAIR = re.compile(r"(coul/long|coul/msm|/long\b|coul/dsf)")


def check(text: str, workdir=None) -> list:
    out = []
    lines = text.splitlines()
    cmds = []
    for n, raw in enumerate(lines, 1):
        s = raw.split("#")[0].strip()
        if s:
            cmds.append((n, s.split()))
    first = {}
    for n, p in cmds:
        first.setdefault(p[0], n)
    units = next((p[1] for n, p in cmds if p[0] == "units" and len(p) > 1), "lj")
    if "units" not in first:
        out.append(Finding("warning", "C01", CHECKS[0][3], None, "units"))
    pair_lines = [(n, " ".join(p)) for n, p in cmds if p[0] == "pair_style"]
    has_long = any(_LONG_PAIR.search(s) for _, s in pair_lines)
    has_kspace = "kspace_style" in first
    if has_long and not has_kspace:
        out.append(Finding("error", "C02", CHECKS[1][3], pair_lines[0][0], "kspace_style"))
    if has_kspace and not has_long:
        out.append(Finding("error", "C03", CHECKS[2][3], first["kspace_style"], "kspace_style"))
    for n, p in cmds:
        if p[0] == "timestep" and len(p) > 1:
            try:
                dt = float(p[1])
            except ValueError:
                continue
            if units in _MAX_DT and dt > _MAX_DT[units]:
                out.append(Finding("warning", "C04", CHECKS[3][3] + " (%s: %g)" % (units, dt), n, "timestep"))
    run_lines = [(n, p) for n, p in cmds if p[0] in ("run", "minimize")]
    if run_lines and ("pair_style" not in first or first["pair_style"] > run_lines[0][0]):
        out.append(Finding("error", "C05", CHECKS[4][3], run_lines[0][0], "run"))
    if "pair_coeff" in first and "pair_style" in first and first["pair_coeff"] < first["pair_style"]:
        out.append(Finding("error", "C06", CHECKS[5][3], first["pair_coeff"], "pair_coeff"))
    active = {}
    for n, p in cmds:
        if p[0] == "fix" and len(p) > 1:
            if p[1] in active:
                out.append(Finding("error", "C07", CHECKS[6][3] + " (%s)" % p[1], n, "fix"))
            active[p[1]] = n
        elif p[0] == "unfix" and len(p) > 1:
            active.pop(p[1], None)
    style = next((p[1] for n, p in cmds if p[0] == "atom_style" and len(p) > 1), "atomic")
    if style in ("bond", "angle", "molecular", "full") and not any(k in first for k in ("read_data", "read_restart", "molecule")):
        out.append(Finding("warning", "C08", CHECKS[7][3], first.get("atom_style"), "atom_style"))
    thermo_n = None
    for n, p in cmds:
        if p[0] == "thermo" and len(p) > 1 and p[1].isdigit():
            thermo_n = (int(p[1]), n)
        if p[0] == "run" and len(p) > 1 and p[1].isdigit() and thermo_n and thermo_n[0] > int(p[1]) > 0:
            out.append(Finding("warning", "C09", CHECKS[8][3] + " (thermo %d, run %s)" % (thermo_n[0], p[1]), thermo_n[1], "thermo"))
    total = sum(int(p[1]) for n, p in cmds if p[0] == "run" and len(p) > 1 and p[1].isdigit())
    for n, p in cmds:
        if p[0] == "dump" and len(p) > 4 and p[4].isdigit() and total and int(p[4]) > total:
            out.append(Finding("warning", "C10", CHECKS[9][3] + " (every %s, total %d)" % (p[4], total), n, "dump"))
    ntypes = next((int(p[1]) for n, p in cmds if p[0] == "create_box" and len(p) > 1 and p[1].isdigit()), None)
    if ntypes:
        mass_lines = [n for n, p in cmds if p[0] == "mass"]
        for n, p in cmds:
            if p[0] != "velocity" or "create" not in p:
                continue
            wildcard_before = any(pp[0] == "mass" and len(pp) > 1 and pp[1] == "*" and nn < n for nn, pp in cmds)
            masses_before = [m for m in mass_lines if m < n]
            if not wildcard_before and len(masses_before) < ntypes:
                out.append(Finding("error", "C11", CHECKS[10][3], n, "velocity"))
                break
    if "timestep" not in first and any(p[0] == "run" for n, p in cmds):
        out.append(Finding("info", "C12", CHECKS[11][3], None, "timestep"))
    if not any(p[0] in ("write_data", "write_restart", "dump") for n, p in cmds):
        out.append(Finding("info", "C13", CHECKS[12][3], None, "write_data"))
    if workdir:
        for n, p in cmds:
            if p[0] == "read_data" and len(p) > 1 and not os.path.exists(os.path.join(workdir, p[1])):
                out.append(Finding("error", "C14", CHECKS[13][3] + " (%s)" % p[1], n, "read_data"))
    return out
